
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###get all
GET {{host}}/blog/posts

###get id
GET {{host}}/blog/post/5e84b17dc797cc4fc939a70d

### create
POST {{host}}/blog/post 
Content-Type: {{contentType}}

{"title": "1","description": "2","body": "3","author": "4","date_posted": "5"}

### update
PUT  {{host}}/blog/edit?postID=5e84b17dc797cc4fc939a70d
Content-Type: {{contentType}}

{"title": "1","description": "2","body": "3","author": "4","date_posted": "5"}

### delete
DELETE  {{host}}/blog/post 
Content-Type: {{contentType}}

{"title": "1","description": "2","body": "3","author": "4","date_posted": "5"}

